# Generated by Django 5.2.11 on 2026-02-11 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "profile_text",
                    models.TextField(
                        blank=True,
                        help_text="QMS programs, procedures, and capabilities already in place. Used to prevent AI from recommending things you already have.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organizations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("root_cause", models.TextField(blank=True)),
                ("recommendation", models.TextField(blank=True)),
                ("impact", models.TextField(blank=True)),
                (
                    "work_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Pipeline Construction", "Pipeline Construction"),
                            ("Compressor Station", "Compressor Station"),
                            ("Meter Station", "Meter Station"),
                            ("HDD/Bore", "HDD/Bore"),
                            ("Hydrostatic Test", "Hydrostatic Test"),
                            ("Tie-In", "Tie-In"),
                            (
                                "Coating/Cathodic Protection",
                                "Coating/Cathodic Protection",
                            ),
                            ("Civil/Earthwork", "Civil/Earthwork"),
                            ("Fabrication", "Fabrication"),
                            ("Commissioning", "Commissioning"),
                            ("Integrity/Repair", "Integrity/Repair"),
                            ("Environmental", "Environmental"),
                            ("Other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "phase",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Pre-Construction", "Pre-Construction"),
                            ("Mobilization", "Mobilization"),
                            ("Construction", "Construction"),
                            ("Mechanical Completion", "Mechanical Completion"),
                            ("Commissioning", "Commissioning"),
                            ("Close-Out", "Close-Out"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "discipline",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Quality", "Quality"),
                            ("Welding", "Welding"),
                            ("NDE", "NDE"),
                            ("Coatings", "Coatings"),
                            ("Civil", "Civil"),
                            ("Mechanical", "Mechanical"),
                            ("Electrical", "Electrical"),
                            ("Environmental", "Environmental"),
                            ("Safety", "Safety"),
                            ("Project Controls", "Project Controls"),
                            ("Materials/Procurement", "Materials/Procurement"),
                            ("Regulatory", "Regulatory"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("Critical", "Critical"),
                            ("High", "High"),
                            ("Medium", "Medium"),
                            ("Low", "Low"),
                        ],
                        default="Medium",
                        max_length=20,
                    ),
                ),
                (
                    "environment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Arctic/Cold Weather", "Arctic/Cold Weather"),
                            ("Desert/Extreme Heat", "Desert/Extreme Heat"),
                            ("Coastal/Saltwater", "Coastal/Saltwater"),
                            ("Wetland/Swamp", "Wetland/Swamp"),
                            ("Mountain/Steep Terrain", "Mountain/Steep Terrain"),
                            ("Urban/Congested", "Urban/Congested"),
                            ("River/Water Crossing", "River/Water Crossing"),
                            ("Normal", "Normal"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "project",
                    models.CharField(
                        blank=True, help_text="Source project name", max_length=255
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=255)),
                (
                    "keywords",
                    models.TextField(
                        blank=True, help_text="Comma-separated keywords/tags"
                    ),
                ),
                ("logged_by", models.CharField(blank=True, max_length=255)),
                ("status", models.CharField(blank=True, max_length=50)),
                ("assigned_to", models.CharField(blank=True, max_length=255)),
                ("supporting_docs", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lessons",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="lessons.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SOWAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(blank=True, max_length=255)),
                ("sow_text", models.TextField()),
                ("work_type", models.CharField(blank=True, max_length=100)),
                (
                    "results",
                    models.JSONField(
                        default=dict, help_text="AI analysis results JSON"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sow_analyses",
                        to="lessons.organization",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "SOW analyses",
                "ordering": ["-created_at"],
            },
        ),
    ]
